In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv('C:/Users/Anubhav Sanyal/Downloads/898ce544-0-MLChallenge_1Datac63af4e/train_indessa.csv')

In [3]:
dataset

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,batch_enrolled,int_rate,grade,sub_grade,emp_title,...,collections_12_mths_ex_med,mths_since_last_major_derog,application_type,verification_status_joint,last_week_pay,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,loan_status
0,58189336,14350,14350,14350.00,36 months,,19.19,E,E3,clerk,...,0.0,74.0,INDIVIDUAL,NaN,26th week,0.0,0.0,28699.0,30800.0,0
1,70011223,4800,4800,4800.00,36 months,BAT1586599,10.99,B,B4,Human Resources Specialist,...,0.0,NaN,INDIVIDUAL,NaN,9th week,0.0,0.0,9974.0,32900.0,0
2,70255675,10000,10000,10000.00,36 months,BAT1586599,7.26,A,A4,Driver,...,0.0,NaN,INDIVIDUAL,NaN,9th week,0.0,65.0,38295.0,34900.0,0
3,1893936,15000,15000,15000.00,36 months,BAT4808022,19.72,D,D5,Us office of Personnel Management,...,0.0,NaN,INDIVIDUAL,NaN,135th week,0.0,0.0,55564.0,24700.0,0
4,7652106,16000,16000,16000.00,36 months,BAT2833642,10.64,B,B2,LAUSD-HOLLYWOOD HIGH SCHOOL,...,0.0,NaN,INDIVIDUAL,NaN,96th week,0.0,0.0,47159.0,47033.0,0
5,10247268,15000,15000,14950.00,36 months,BAT2575549,8.90,A,A5,Design Consultant,...,0.0,NaN,INDIVIDUAL,NaN,113th week,0.0,0.0,350619.0,29500.0,0
6,8089625,5000,5000,4975.00,36 months,,7.90,A,A4,TOYOTA OF NORTH HOLLYWOOD,...,0.0,NaN,INDIVIDUAL,NaN,117th week,0.0,1023.0,13272.0,55500.0,1
7,23043116,6000,6000,6000.00,36 months,NaN,9.17,B,B1,Banker,...,0.0,54.0,INDIVIDUAL,NaN,78th week,0.0,0.0,272579.0,11800.0,0
8,45900933,6000,6000,6000.00,36 months,BAT4136152,13.99,C,C4,LVN,...,0.0,NaN,INDIVIDUAL,NaN,44th week,0.0,0.0,281521.0,62100.0,0
9,41272507,34550,34550,34550.00,60 months,BAT4694572,17.14,D,D4,Registered Nurse,...,0.0,NaN,INDIVIDUAL,NaN,52th week,0.0,0.0,76034.0,33200.0,0
10,56621560,25000,25000,24975.00,36 months,,13.33,C,C3,VP of Operations,...,0.0,52.0,INDIVIDUAL,NaN,26th week,0.0,0.0,72193.0,47000.0,0
11,4221941,15000,15000,15000.00,36 months,,18.49,D,D2,Jp Morgan chase bank,...,0.0,82.0,INDIVIDUAL,NaN,95th week,0.0,0.0,39152.0,19600.0,1
12,43387539,18000,18000,18000.00,36 months,BAT5924421,6.99,A,A3,driver,...,0.0,NaN,INDIVIDUAL,NaN,48th week,0.0,0.0,194011.0,139900.0,0
13,23001903,9000,9000,9000.00,36 months,BAT3193689,6.03,A,A1,Federal Law Enforcement,...,0.0,NaN,INDIVIDUAL,NaN,78th week,0.0,0.0,165164.0,43000.0,0
14,13670372,8800,8800,8800.00,36 months,BAT224923,13.65,C,C1,Truck Driver,...,0.0,NaN,INDIVIDUAL,NaN,82th week,0.0,0.0,39634.0,41200.0,1
15,49874851,8000,8000,8000.00,36 months,BAT1184694,15.61,D,D1,ASSISTANT QAPI COORDINATOR,...,0.0,NaN,INDIVIDUAL,NaN,35th week,0.0,0.0,48488.0,18500.0,0
16,9878144,18450,18450,18450.00,60 months,BAT1930365,21.70,E,E2,LS1,...,0.0,72.0,INDIVIDUAL,NaN,96th week,0.0,0.0,71191.0,15900.0,0
17,12866989,30750,30750,30700.00,36 months,,16.99,D,D1,NaN,...,0.0,26.0,INDIVIDUAL,NaN,104th week,0.0,0.0,221335.0,17400.0,0
18,58568833,9000,9000,9000.00,36 months,BAT3873588,9.99,B,B3,Production employee,...,0.0,NaN,INDIVIDUAL,NaN,26th week,0.0,0.0,34538.0,17000.0,0
19,62725253,24000,24000,24000.00,36 months,NaN,10.99,B,B4,Principal Consultant,...,0.0,NaN,INDIVIDUAL,NaN,17th week,0.0,0.0,125903.0,31000.0,0
20,66791957,20000,20000,20000.00,60 months,BAT2252229,17.86,D,D5,Zone business manager,...,0.0,18.0,INDIVIDUAL,NaN,13th week,0.0,0.0,66738.0,27200.0,0
21,1699807,12400,12400,12400.00,36 months,BAT1135695,6.62,A,A2,Expeditors,...,0.0,NaN,INDIVIDUAL,NaN,NAth week,0.0,NaN,NaN,NaN,0
22,54486146,4200,4200,4200.00,36 months,,17.57,D,D4,production coordinator,...,0.0,NaN,INDIVIDUAL,NaN,31th week,0.0,0.0,282808.0,25700.0,0
23,41408977,10500,10500,10500.00,36 months,BAT4694572,13.66,C,C3,Title Manager,...,0.0,NaN,INDIVIDUAL,NaN,30th week,0.0,0.0,71697.0,14300.0,1
24,63047232,16000,16000,16000.00,36 months,BAT4271519,7.89,A,A5,Coordinator,...,0.0,NaN,INDIVIDUAL,NaN,17th week,0.0,0.0,147448.0,41400.0,0
25,22741274,23800,23800,23800.00,60 months,,15.61,D,D1,Quality Engineer,...,0.0,NaN,INDIVIDUAL,NaN,78th week,0.0,0.0,327930.0,43400.0,0
26,17563299,7200,7200,7150.00,36 months,NaN,12.99,C,C1,Top shelf sales,...,0.0,47.0,INDIVIDUAL,NaN,70th week,0.0,0.0,8589.0,19800.0,1
27,10317534,19200,19200,19175.00,36 months,NaN,6.62,A,A2,Physician,...,0.0,NaN,INDIVIDUAL,NaN,104th week,0.0,0.0,447388.0,33100.0,1
28,50609137,15000,15000,15000.00,36 months,BAT1184694,6.92,A,A4,Teacher,...,0.0,NaN,INDIVIDUAL,NaN,35th week,0.0,0.0,114298.0,49900.0,0
29,70008968,4000,4000,4000.00,36 months,BAT1586599,17.57,D,D4,cna,...,0.0,NaN,INDIVIDUAL,NaN,4th week,0.0,0.0,31445.0,10900.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
532398,23543780,18000,18000,18000.00,36 months,BAT3193689,14.49,C,C4,Owner,...,0.0,52.0,INDIVIDUAL,NaN,78th week,0.0,0.0,429344.0,9000.0,0
532399,16543128,4700,4700,4700.00,36 months,BAT5489674,11.99,B,B3,PATIENT ACCESS,...,0.0,NaN,INDIVIDUAL,NaN,17th week,0.0,0.0,101351.0,7300.0,1
532400,73414202,20000,20000,20000.00,36 months,NaN,9.17,B,B2,utility,...,0.0,NaN,INDIVIDUAL,NaN,NAth week,0.0,0.0,69832.0,25900.0,0
532401,54776171,7800,7800,7800.00,36 months,BAT3726927,9.99,B,B3,Owner,...,0.0,74.0,INDIVIDUAL,NaN,31th week,0.0,0.0,46121.0,21200.0,0
532402,52377140,10400,10400,10400.00,36 months,BAT3726927,7.26,A,A4,Mechanic,...,0.0,NaN,INDIVIDUAL,NaN,31th week,0.0,0.0,116826.0,22400.0,0
532403,59468945,22375,22375,22375.00,60 months,BAT3873588,19.19,E,E3,IT Systems Engineer,...,0.0,NaN,INDIVIDUAL,NaN,26th week,0.0,0.0,21055.0,13000.0,0
532404,68127956,8000,8000,8000.00,36 months,BAT1586599,7.26,A,A4,Senior Engineering Manager,...,0.0,70.0,INDIVIDUAL,NaN,9th week,0.0,0.0,279875.0,51100.0,0
532405,5906972,18000,18000,18000.00,60 months,BAT4808022,17.27,C,C5,Department of Justice,...,0.0,NaN,INDIVIDUAL,NaN,100th week,0.0,0.0,68068.0,27800.0,1
532406,70600730,10000,10000,10000.00,36 months,BAT2803411,6.24,A,A2,Designer,...,0.0,NaN,INDIVIDUAL,NaN,4th week,0.0,0.0,75747.0,17000.0,0
532407,59780170,16000,16000,16000.00,36 months,BAT3873588,7.26,A,A4,Small Business Consultant,...,0.0,NaN,INDIVIDUAL,NaN,26th week,0.0,0.0,45671.0,16100.0,0
532408,69555199,7200,7200,7200.00,36 months,BAT1586599,9.17,B,B2,Funeral Director/Grief Counselor,...,0.0,NaN,INDIVIDUAL,NaN,9th week,0.0,0.0,145019.0,26300.0,0
532409,4583654,17625,17625,17625.00,36 months,BAT5714674,16.29,C,C4,unistrut corp.,...,0.0,NaN,INDIVIDUAL,NaN,126th week,0.0,0.0,30960.0,33000.0,0
532410,272515,9700,9700,8283.54,36 months,,14.82,E,E3,Hilton Hotels,...,0.0,NaN,INDIVIDUAL,NaN,156th week,0.0,NaN,NaN,NaN,1
532411,10340541,20000,20000,20000.00,36 months,BAT2575549,9.67,B,B1,sr operator,...,0.0,NaN,INDIVIDUAL,NaN,78th week,0.0,0.0,166357.0,35800.0,1
532412,48073747,7200,7200,7200.00,36 months,BAT1104812,16.55,D,D2,CNC Operator,...,0.0,NaN,INDIVIDUAL,NaN,39th week,0.0,0.0,35503.0,5400.0,0
532413,12956724,19200,19200,19200.00,60 months,BAT1766061,19.22,D,D4,Cyber Security Advisor,...,0.0,NaN,INDIVIDUAL,NaN,100th week,0.0,0.0,556189.0,45100.0,0
532414,26517526,20000,20000,20000.00,36 months,NaN,14.49,C,C4,AVP,...,0.0,68.0,INDIVIDUAL,NaN,70th week,0.0,0.0,36011.0,15900.0,0
532415,965370,10000,10000,10000.00,36 months,,7.49,A,A4,Lockheed Martin,...,0.0,NaN,INDIVIDUAL,NaN,161th week,0.0,NaN,NaN,NaN,1
532416,19786238,1800,1800,1800.00,36 months,NaN,16.99,D,D3,Content Specialist,...,0.0,NaN,INDIVIDUAL,NaN,83th week,0.0,128.0,137538.0,42100.0,0
532417,68700956,10000,10000,10000.00,36 months,BAT1586599,9.99,B,B3,Staffing assistant,...,0.0,NaN,INDIVIDUAL,NaN,9th week,0.0,2070.0,15552.0,18300.0,0
532418,71054913,10000,10000,10000.00,36 months,NaN,9.76,B,B3,Teacher,...,0.0,NaN,INDIVIDUAL,NaN,4th week,0.0,890.0,121294.0,19700.0,0
532419,51774468,4800,4800,4800.00,36 months,BAT1184694,11.53,B,B5,Help Desk Technician,...,0.0,NaN,INDIVIDUAL,NaN,31th week,0.0,0.0,24985.0,10400.0,0
532420,16661491,5700,5700,5700.00,36 months,BAT5489674,14.16,C,C2,Admin Secretary,...,0.0,NaN,INDIVIDUAL,NaN,4th week,0.0,0.0,89997.0,15600.0,1
532421,32097538,13000,13000,13000.00,60 months,BAT2078974,12.99,C,C1,Teacher,...,0.0,7.0,INDIVIDUAL,NaN,65th week,0.0,0.0,11231.0,26900.0,0
532422,8219842,10000,10000,10000.00,36 months,NaN,14.33,C,C2,Champion Mortgage,...,0.0,NaN,INDIVIDUAL,NaN,22th week,0.0,0.0,189233.0,24200.0,1
532423,31296187,20000,20000,20000.00,36 months,,12.49,B,B5,Registered Nurse,...,0.0,NaN,INDIVIDUAL,NaN,65th week,0.0,0.0,83087.0,24800.0,0
532424,29403184,12000,12000,12000.00,60 months,BAT2003848,14.99,C,C5,Account Mgr,...,0.0,NaN,INDIVIDUAL,NaN,70th week,0.0,0.0,227812.0,17800.0,0
532425,7357607,18725,18725,18725.00,60 months,NaN,20.80,E,E1,Comcast cable,...,0.0,NaN,INDIVIDUAL,NaN,9th week,0.0,0.0,26010.0,24200.0,1
532426,23182668,21000,21000,21000.00,60 months,BAT3193689,16.29,D,D2,Resident Physician,...,0.0,NaN,INDIVIDUAL,NaN,78th week,0.0,0.0,29197.0,23300.0,0
532427,46122259,10000,10000,10000.00,36 months,BAT4136152,6.39,A,A2,Health Care Analyst,...,0.0,NaN,INDIVIDUAL,NaN,44th week,0.0,0.0,47866.0,21700.0,0

In [4]:
dataset=dataset.drop(dataset.columns[[0,5,7,8,9,11,13,14,15,16,17,18,19,30,37,]], axis=1)

In [5]:
dataset.term[dataset.term== "36 months"] =36
dataset.term[dataset.term== "60 months"] =60

C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [6]:
dataset.emp_length[dataset.emp_length== '9 years']=9
dataset.emp_length[dataset.emp_length== '8 years']=8
dataset.emp_length[dataset.emp_length== '7 years']=7
dataset.emp_length[dataset.emp_length== '6 years']=6
dataset.emp_length[dataset.emp_length== '5 years']=5
dataset.emp_length[dataset.emp_length== '4 years']=4
dataset.emp_length[dataset.emp_length== '3 years']=3
dataset.emp_length[dataset.emp_length== '2 years']=2
dataset.emp_length[dataset.emp_length== '1 year']=1
dataset.emp_length[dataset.emp_length== '10+ years']=11
dataset.emp_length[dataset.emp_length== '< 1 year']=0.5

C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()

In [7]:
dataset

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,emp_length,annual_inc,dti,delinq_2yrs,inq_last_6mths,...,collection_recovery_fee,collections_12_mths_ex_med,mths_since_last_major_derog,verification_status_joint,last_week_pay,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,loan_status
0,14350,14350,14350.00,36,19.19,9,28700.0,33.88,0.0,1.0,...,0.00,0.0,74.0,NaN,26th week,0.0,0.0,28699.0,30800.0,0
1,4800,4800,4800.00,36,10.99,0.5,65000.0,3.64,0.0,1.0,...,0.00,0.0,NaN,NaN,9th week,0.0,0.0,9974.0,32900.0,0
2,10000,10000,10000.00,36,7.26,2,45000.0,18.42,0.0,0.0,...,0.00,0.0,NaN,NaN,9th week,0.0,65.0,38295.0,34900.0,0
3,15000,15000,15000.00,36,19.72,11,105000.0,14.97,0.0,2.0,...,0.00,0.0,NaN,NaN,135th week,0.0,0.0,55564.0,24700.0,0
4,16000,16000,16000.00,36,10.64,11,52000.0,20.16,0.0,0.0,...,0.00,0.0,NaN,NaN,96th week,0.0,0.0,47159.0,47033.0,0
5,15000,15000,14950.00,36,8.90,2,120000.0,12.30,0.0,0.0,...,0.00,0.0,NaN,NaN,113th week,0.0,0.0,350619.0,29500.0,0
6,5000,5000,4975.00,36,7.90,5,75000.0,5.70,0.0,0.0,...,0.00,0.0,NaN,NaN,117th week,0.0,1023.0,13272.0,55500.0,1
7,6000,6000,6000.00,36,9.17,8,54000.0,11.63,0.0,1.0,...,0.00,0.0,54.0,NaN,78th week,0.0,0.0,272579.0,11800.0,0
8,6000,6000,6000.00,36,13.99,7,92000.0,30.85,0.0,0.0,...,0.00,0.0,NaN,NaN,44th week,0.0,0.0,281521.0,62100.0,0
9,34550,34550,34550.00,60,17.14,2,72000.0,33.92,0.0,0.0,...,0.00,0.0,NaN,NaN,52th week,0.0,0.0,76034.0,33200.0,0
10,25000,25000,24975.00,36,13.33,11,135000.0,14.20,0.0,1.0,...,0.00,0.0,52.0,NaN,26th week,0.0,0.0,72193.0,47000.0,0
11,15000,15000,15000.00,36,18.49,4,76000.0,15.86,0.0,1.0,...,0.00,0.0,82.0,NaN,95th week,0.0,0.0,39152.0,19600.0,1
12,18000,18000,18000.00,36,6.99,7,62000.0,18.58,0.0,2.0,...,0.00,0.0,NaN,NaN,48th week,0.0,0.0,194011.0,139900.0,0
13,9000,9000,9000.00,36,6.03,11,145000.0,15.42,0.0,0.0,...,0.00,0.0,NaN,NaN,78th week,0.0,0.0,165164.0,43000.0,0
14,8800,8800,8800.00,36,13.65,11,80000.0,13.98,0.0,1.0,...,0.00,0.0,NaN,NaN,82th week,0.0,0.0,39634.0,41200.0,1
15,8000,8000,8000.00,36,15.61,4,50000.0,27.39,0.0,2.0,...,0.00,0.0,NaN,NaN,35th week,0.0,0.0,48488.0,18500.0,0
16,18450,18450,18450.00,60,21.70,9,69000.0,24.28,0.0,0.0,...,0.00,0.0,72.0,NaN,96th week,0.0,0.0,71191.0,15900.0,0
17,30750,30750,30700.00,36,16.99,NaN,70000.0,29.13,3.0,2.0,...,0.00,0.0,26.0,NaN,104th week,0.0,0.0,221335.0,17400.0,0
18,9000,9000,9000.00,36,9.99,7,60000.0,19.70,0.0,0.0,...,0.00,0.0,NaN,NaN,26th week,0.0,0.0,34538.0,17000.0,0
19,24000,24000,24000.00,36,10.99,7,130000.0,23.22,0.0,1.0,...,0.00,0.0,NaN,NaN,17th week,0.0,0.0,125903.0,31000.0,0
20,20000,20000,20000.00,60,17.86,9,96000.0,18.31,1.0,0.0,...,0.00,0.0,18.0,NaN,13th week,0.0,0.0,66738.0,27200.0,0
21,12400,12400,12400.00,36,6.62,2,40000.0,20.31,0.0,2.0,...,7.03,0.0,NaN,NaN,NAth week,0.0,NaN,NaN,NaN,0
22,4200,4200,4200.00,36,17.57,11,46000.0,31.25,1.0,0.0,...,0.00,0.0,NaN,NaN,31th week,0.0,0.0,282808.0,25700.0,0
23,10500,10500,10500.00,36,13.66,7,60000.0,13.82,0.0,1.0,...,0.00,0.0,NaN,NaN,30th week,0.0,0.0,71697.0,14300.0,1
24,16000,16000,16000.00,36,7.89,0.5,65000.0,21.54,0.0,0.0,...,0.00,0.0,NaN,NaN,17th week,0.0,0.0,147448.0,41400.0,0
25,23800,23800,23800.00,60,15.61,4,70000.0,21.93,0.0,0.0,...,0.00,0.0,NaN,NaN,78th week,0.0,0.0,327930.0,43400.0,0
26,7200,7200,7150.00,36,12.99,2,37000.0,13.43,0.0,0.0,...,0.00,0.0,47.0,NaN,70th week,0.0,0.0,8589.0,19800.0,1
27,19200,19200,19175.00,36,6.62,1,250000.0,25.86,0.0,1.0,...,0.00,0.0,NaN,NaN,104th week,0.0,0.0,447388.0,33100.0,1
28,15000,15000,15000.00,36,6.92,3,90000.0,29.68,0.0,1.0,...,0.00,0.0,NaN,NaN,35th week,0.0,0.0,114298.0,49900.0,0
29,4000,4000,4000.00,36,17.57,2,20000.0,30.79,0.0,0.0,...,0.00,0.0,NaN,NaN,4th week,0.0,0.0,31445.0,10900.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
532398,18000,18000,18000.00,36,14.49,7,75000.0,16.03,3.0,1.0,...,0.00,0.0,52.0,NaN,78th week,0.0,0.0,429344.0,9000.0,0
532399,4700,4700,4700.00,36,11.99,9,30000.0,17.40,0.0,0.0,...,0.00,0.0,NaN,NaN,17th week,0.0,0.0,101351.0,7300.0,1
532400,20000,20000,20000.00,36,9.17,4,94000.0,28.25,0.0,0.0,...,0.00,0.0,NaN,NaN,NAth week,0.0,0.0,69832.0,25900.0,0
532401,7800,7800,7800.00,36,9.99,0.5,77500.0,23.36,0.0,1.0,...,0.00,0.0,74.0,NaN,31th week,0.0,0.0,46121.0,21200.0,0
532402,10400,10400,10400.00,36,7.26,0.5,50000.0,29.40,1.0,1.0,...,0.00,0.0,NaN,NaN,31th week,0.0,0.0,116826.0,22400.0,0
532403,22375,22375,22375.00,60,19.19,11,128000.0,5.63,0.0,1.0,...,0.00,0.0,NaN,NaN,26th week,0.0,0.0,21055.0,13000.0,0
532404,8000,8000,8000.00,36,7.26,11,123000.0,24.57,0.0,1.0,...,0.00,0.0,70.0,NaN,9th week,0.0,0.0,279875.0,51100.0,0
532405,18000,18000,18000.00,60,17.27,3,62000.0,26.03,1.0,1.0,...,0.00,0.0,NaN,NaN,100th week,0.0,0.0,68068.0,27800.0,1
532406,10000,10000,10000.00,36,6.24,2,56000.0,11.06,0.0,1.0,...,0.00,0.0,NaN,NaN,4th week,0.0,0.0,75747.0,17000.0,0
532407,16000,16000,16000.00,36,7.26,11,54000.0,26.31,0.0,0.0,...,0.00,0.0,NaN,NaN,26th week,0.0,0.0,45671.0,16100.0,0
532408,7200,7200,7200.00,36,9.17,11,70000.0,14.62,0.0,0.0,...,0.00,0.0,NaN,NaN,9th week,0.0,0.0,145019.0,26300.0,0
532409,17625,17625,17625.00,36,16.29,11,41000.0,15.83,0.0,1.0,...,0.00,0.0,NaN,NaN,126th week,0.0,0.0,30960.0,33000.0,0
532410,9700,9700,8283.54,36,14.82,1,37500.0,27.04,0.0,5.0,...,0.00,0.0,NaN,NaN,156th week,0.0,NaN,NaN,NaN,1
532411,20000,20000,20000.00,36,9.67,6,78000.0,29.23,0.0,1.0,...,0.00,0.0,NaN,NaN,78th week,0.0,0.0,166357.0,35800.0,1
532412,7200,7200,7200.00,36,16.55,6,50000.0,23.79,0.0,2.0,...,0.00,0.0,NaN,NaN,39th week,0.0,0.0,35503.0,5400.0,0
532413,19200,19200,19200.00,60,19.22,11,153000.0,16.91,0.0,4.0,...,0.00,0.0,NaN,NaN,100th week,0.0,0.0,556189.0,45100.0,0
532414,20000,20000,20000.00,36,14.49,7,120000.0,9.17,0.0,0.0,...,0.00,0.0,68.0,NaN,70th week,0.0,0.0,36011.0,15900.0,0
532415,10000,10000,10000.00,36,7.49,6,60000.0,24.46,0.0,1.0,...,0.00,0.0,NaN,NaN,161th week,0.0,NaN,NaN,NaN,1
532416,1800,1800,1800.00,36,16.99,11,62000.0,22.45,0.0,1.0,...,0.00,0.0,NaN,NaN,83th week,0.0,128.0,137538.0,42100.0,0
532417,10000,10000,10000.00,36,9.99,11,60000.0,19.54,0.0,0.0,...,0.00,0.0,NaN,NaN,9th week,0.0,2070.0,15552.0,18300.0,0
532418,10000,10000,10000.00,36,9.76,9,54000.0,25.07,0.0,0.0,...,0.00,0.0,NaN,NaN,4th week,0.0,890.0,121294.0,19700.0,0
532419,4800,4800,4800.00,36,11.53,0.5,45000.0,7.97,1.0,0.0,...,0.00,0.0,NaN,NaN,31th week,0.0,0.0,24985.0,10400.0,0
532420,5700,5700,5700.00,36,14.16,9,37000.0,25.36,0.0,3.0,...,0.00,0.0,NaN,NaN,4th week,0.0,0.0,89997.0,15600.0,1
532421,13000,13000,13000.00,60,12.99,3,55000.0,4.65,1.0,0.0,...,0.00,0.0,7.0,NaN,65th week,0.0,0.0,11231.0,26900.0,0
532422,10000,10000,10000.00,36,14.33,11,49900.0,20.20,0.0,1.0,...,0.00,0.0,NaN,NaN,22th week,0.0,0.0,189233.0,24200.0,1
532423,20000,20000,20000.00,36,12.49,11,75000.0,14.53,0.0,0.0,...,0.00,0.0,NaN,NaN,65th week,0.0,0.0,83087.0,24800.0,0
532424,12000,12000,12000.00,60,14.99,11,59000.0,22.97,0.0,0.0,...,0.00,0.0,NaN,NaN,70th week,0.0,0.0,227812.0,17800.0,0
532425,18725,18725,18725.00,60,20.80,8,42504.0,27.27,0.0,1.0,...,0.00,0.0,NaN,NaN,9th week,0.0,0.0,26010.0,24200.0,1
532426,21000,21000,21000.00,60,16.29,1,50000.0,14.91,0.0,1.0,...,0.00,0.0,NaN,NaN,78th week,0.0,0.0,29197.0,23300.0,0
532427,10000,10000,10000.00,36,6.39,0.5,53000.0,17.80,0.0,0.0,...,0.00,0.0,NaN,NaN,44th week,0.0,0.0,47866.0,21700.0,0

In [81]:
dataset=dataset.drop(dataset.columns[[21,23,24]],axis=1)

In [82]:
dataset

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,emp_length,annual_inc,dti,delinq_2yrs,inq_last_6mths,...,revol_util,total_acc,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,mths_since_last_major_derog,tot_cur_bal,total_rev_hi_lim,loan_status
0,14350,14350,14350.00,36,19.19,9.000000,28700.0,33.88,0.0,1.0,...,73.1,28.0,1173.84,0.00,0.00,0.00,74.000000,0.000000,30800.000000,0
1,4800,4800,4800.00,36,10.99,0.500000,65000.0,3.64,0.0,1.0,...,23.2,13.0,83.95,0.00,0.00,0.00,44.121462,0.000000,32900.000000,0
2,10000,10000,10000.00,36,7.26,2.000000,45000.0,18.42,0.0,0.0,...,31.2,19.0,56.47,0.00,0.00,0.00,44.121462,65.000000,34900.000000,0
3,15000,15000,15000.00,36,19.72,11.000000,105000.0,14.97,0.0,2.0,...,55.5,21.0,4858.62,0.00,0.00,0.00,44.121462,0.000000,24700.000000,0
4,16000,16000,16000.00,36,10.64,11.000000,52000.0,20.16,0.0,0.0,...,76.2,27.0,2296.41,0.00,0.00,0.00,44.121462,0.000000,47033.000000,0
5,15000,15000,14950.00,36,8.90,2.000000,120000.0,12.30,0.0,0.0,...,64.5,30.0,1957.24,0.00,0.00,0.00,44.121462,0.000000,29500.000000,0
6,5000,5000,4975.00,36,7.90,5.000000,75000.0,5.70,0.0,0.0,...,23.9,23.0,578.36,0.00,0.00,0.00,44.121462,1023.000000,55500.000000,1
7,6000,6000,6000.00,36,9.17,8.000000,54000.0,11.63,0.0,1.0,...,29.5,49.0,637.51,0.00,0.00,0.00,54.000000,0.000000,11800.000000,0
8,6000,6000,6000.00,36,13.99,7.000000,92000.0,30.85,0.0,0.0,...,76.6,27.0,621.72,0.00,0.00,0.00,44.121462,0.000000,62100.000000,0
9,34550,34550,34550.00,60,17.14,2.000000,72000.0,33.92,0.0,0.0,...,90.5,30.0,5535.46,0.00,0.00,0.00,44.121462,0.000000,33200.000000,0
10,25000,25000,24975.00,36,13.33,11.000000,135000.0,14.20,0.0,1.0,...,50.8,32.0,1551.58,0.00,0.00,0.00,52.000000,0.000000,47000.000000,0
11,15000,15000,15000.00,36,18.49,4.000000,76000.0,15.86,0.0,1.0,...,71.9,30.0,3726.32,0.00,0.00,0.00,82.000000,0.000000,19600.000000,1
12,18000,18000,18000.00,36,6.99,7.000000,62000.0,18.58,0.0,2.0,...,34.2,31.0,992.37,0.00,0.00,0.00,44.121462,0.000000,139900.000000,0
13,9000,9000,9000.00,36,6.03,11.000000,145000.0,15.42,0.0,0.0,...,27.2,39.0,633.42,0.00,0.00,0.00,44.121462,0.000000,43000.000000,0
14,8800,8800,8800.00,36,13.65,11.000000,80000.0,13.98,0.0,1.0,...,41.4,17.0,1521.50,0.00,0.00,0.00,44.121462,0.000000,41200.000000,1
15,8000,8000,8000.00,36,15.61,4.000000,50000.0,27.39,0.0,2.0,...,35.4,24.0,801.55,0.00,0.00,0.00,44.121462,0.000000,18500.000000,0
16,18450,18450,18450.00,60,21.70,9.000000,69000.0,24.28,0.0,0.0,...,96.2,35.0,6269.20,0.00,0.00,0.00,72.000000,0.000000,15900.000000,0
17,30750,30750,30700.00,36,16.99,6.398724,70000.0,29.13,3.0,2.0,...,99.4,35.0,7394.32,0.00,0.00,0.00,26.000000,0.000000,17400.000000,0
18,9000,9000,9000.00,36,9.99,7.000000,60000.0,19.70,0.0,0.0,...,54.7,28.0,412.36,0.00,0.00,0.00,44.121462,0.000000,17000.000000,0
19,24000,24000,24000.00,36,10.99,7.000000,130000.0,23.22,0.0,1.0,...,76.7,25.0,833.27,0.00,0.00,0.00,44.121462,0.000000,31000.000000,0
20,20000,20000,20000.00,60,17.86,9.000000,96000.0,18.31,1.0,0.0,...,68.7,28.0,843.95,0.00,0.00,0.00,18.000000,0.000000,27200.000000,0
21,12400,12400,12400.00,36,6.62,2.000000,40000.0,20.31,0.0,2.0,...,12.2,9.0,0.00,0.00,712.76,7.03,44.121462,213.562222,32080.572919,0
22,4200,4200,4200.00,36,17.57,11.000000,46000.0,31.25,1.0,0.0,...,82.4,28.0,394.08,0.00,0.00,0.00,44.121462,0.000000,25700.000000,0
23,10500,10500,10500.00,36,13.66,7.000000,60000.0,13.82,0.0,1.0,...,60.6,24.0,845.33,0.00,0.00,0.00,44.121462,0.000000,14300.000000,1
24,16000,16000,16000.00,36,7.89,0.500000,65000.0,21.54,0.0,0.0,...,54.2,30.0,398.12,0.00,0.00,0.00,44.121462,0.000000,41400.000000,0
25,23800,23800,23800.00,60,15.61,4.000000,70000.0,21.93,0.0,0.0,...,46.7,27.0,5008.50,0.00,0.00,0.00,44.121462,0.000000,43400.000000,0
26,7200,7200,7150.00,36,12.99,2.000000,37000.0,13.43,0.0,0.0,...,32.0,28.0,1047.06,0.00,0.00,0.00,47.000000,0.000000,19800.000000,1
27,19200,19200,19175.00,36,6.62,1.000000,250000.0,25.86,0.0,1.0,...,87.3,23.0,1785.13,0.00,0.00,0.00,44.121462,0.000000,33100.000000,1
28,15000,15000,15000.00,36,6.92,3.000000,90000.0,29.68,0.0,1.0,...,48.4,31.0,624.80,0.00,0.00,0.00,44.121462,0.000000,49900.000000,0
29,4000,4000,4000.00,36,17.57,2.000000,20000.0,30.79,0.0,0.0,...,58.1,9.0,52.71,0.00,0.00,0.00,44.121462,0.000000,10900.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
532398,18000,18000,18000.00,36,14.49,7.000000,75000.0,16.03,3.0,1.0,...,55.8,27.0,3119.27,0.00,0.00,0.00,52.000000,0.000000,9000.000000,0
532399,4700,4700,4700.00,36,11.99,9.000000,30000.0,17.40,0.0,0.0,...,59.5,21.0,181.26,0.00,0.00,0.00,44.121462,0.000000,7300.000000,1
532400,20000,20000,20000.00,36,9.17,4.000000,94000.0,28.25,0.0,0.0,...,46.7,31.0,0.00,0.00,0.00,0.00,44.121462,0.000000,25900.000000,0
532401,7800,7800,7800.00,36,9.99,0.500000,77500.0,23.36,0.0,1.0,...,64.5,22.0,417.12,0.00,0.00,0.00,74.000000,0.000000,21200.000000,0
532402,10400,10400,10400.00,36,7.26,0.500000,50000.0,29.40,1.0,1.0,...,55.8,25.0,402.95,0.00,0.00,0.00,44.121462,0.000000,22400.000000,0
532403,22375,22375,22375.00,60,19.19,11.000000,128000.0,5.63,0.0,1.0,...,71.0,19.0,1728.66,0.00,0.00,0.00,44.121462,0.000000,13000.000000,0
532404,8000,8000,8000.00,36,7.26,11.000000,123000.0,24.57,0.0,1.0,...,44.7,59.0,91.11,0.00,0.00,0.00,70.000000,0.000000,51100.000000,0
532405,18000,18000,18000.00,60,17.27,3.000000,62000.0,26.03,1.0,1.0,...,83.4,26.0,4778.11,0.00,0.00,0.00,44.121462,0.000000,27800.000000,1
532406,10000,10000,10000.00,36,6.24,2.000000,56000.0,11.06,0.0,1.0,...,64.0,14.0,56.62,0.00,0.00,0.00,44.121462,0.000000,17000.000000,0
532407,16000,16000,16000.00,36,7.26,11.000000,54000.0,26.31,0.0,0.0,...,81.7,11.0,446.80,0.00,0.00,0.00,44.121462,0.000000,16100.000000,0
532408,7200,7200,7200.00,36,9.17,11.000000,70000.0,14.62,0.0,0.0,...,41.0,21.0,101.37,0.00,0.00,0.00,44.121462,0.000000,26300.000000,0
532409,17625,17625,17625.00,36,16.29,11.000000,41000.0,15.83,0.0,1.0,...,93.8,16.0,4545.31,0.00,0.00,0.00,44.121462,0.000000,33000.000000,0
532410,9700,9700,8283.54,36,14.82,1.000000,37500.0,27.04,0.0,5.0,...,78.6,30.0,2367.53,0.00,0.00,0.00,44.121462,213.562222,32080.572919,1
532411,20000,20000,20000.00,36,9.67,6.000000,78000.0,29.23,0.0,1.0,...,17.6,25.0,2295.31,0.00,0.00,0.00,44.121462,0.000000,35800.000000,1
532412,7200,7200,7200.00,36,16.55,6.000000,50000.0,23.79,0.0,2.0,...,24.2,29.0,800.56,0.00,0.00,0.00,44.121462,0.000000,5400.000000,0
532413,19200,19200,19200.00,60,19.22,11.000000,153000.0,16.91,0.0,4.0,...,65.8,32.0,6206.47,25.02,0.00,0.00,44.121462,0.000000,45100.000000,0
532414,20000,20000,20000.00,36,14.49,7.000000,120000.0,9.17,0.0,0.0,...,80.8,25.0,3178.58,0.00,0.00,0.00,68.000000,0.000000,15900.000000,0
532415,10000,10000,10000.00,36,7.49,6.000000,60000.0,24.46,0.0,1.0,...,8.9,34.0,1193.39,0.00,0.00,0.00,44.121462,213.562222,32080.572919,1
532416,1800,1800,1800.00,36,16.99,11.000000,62000.0,22.45,0.0,1.0,...,78.1,30.0,382.60,0.00,0.00,0.00,44.121462,128.000000,42100.000000,0
532417,10000,10000,10000.00,36,9.99,11.000000,60000.0,19.54,0.0,0.0,...,46.0,28.0,158.82,0.00,0.00,0.00,44.121462,2070.000000,18300.000000,0
532418,10000,10000,10000.00,36,9.76,9.000000,54000.0,25.07,0.0,0.0,...,70.3,35.0,75.91,0.00,0.00,0.00,44.121462,890.000000,19700.000000,0
532419,4800,4800,4800.00,36,11.53,0.500000,45000.0,7.97,1.0,0.0,...,43.8,23.0,308.18,0.00,0.00,0.00,44.121462,0.000000,10400.000000,0
532420,5700,5700,5700.00,36,14.16,9.000000,37000.0,25.36,0.0,3.0,...,63.7,35.0,67.26,0.00,0.00,0.00,44.121462,0.000000,15600.000000,1
532421,13000,13000,13000.00,60,12.99,3.000000,55000.0,4.65,1.0,0.0,...,24.7,25.0,1916.77,0.00,0.00,0.00,7.000000,0.000000,26900.000000,0
532422,10000,10000,10000.00,36,14.33,11.000000,49900.0,20.20,0.0,1.0,...,60.0,17.0,569.12,0.00,0.00,0.00,44.121462,0.000000,24200.000000,1
532423,20000,20000,20000.00,36,12.49,11.000000,75000.0,14.53,0.0,0.0,...,63.6,34.0,2595.45,0.00,0.00,0.00,44.121462,0.000000,24800.000000,0
532424,12000,12000,12000.00,60,14.99,11.000000,59000.0,22.97,0.0,0.0,...,53.1,29.0,2182.92,0.00,0.00,0.00,44.121462,0.000000,17800.000000,0
532425,18725,18725,18725.00,60,20.80,8.000000,42504.0,27.27,0.0,1.0,...,49.9,26.0,645.32,0.00,0.00,0.00,44.121462,0.000000,24200.000000,1
532426,21000,21000,21000.00,60,16.29,1.000000,50000.0,14.91,0.0,1.0,...,89.7,14.0,4619.79,0.00,0.00,0.00,44.121462,0.000000,23300.000000,0
532427,10000,10000,10000.00,36,6.39,0.500000,53000.0,17.80,0.0,0.0,...,46.4,20.0,467.52,0.00,0.00,0.00,44.121462,0.000000,21700.000000,0

In [86]:
dataset['loan_amnt'] = dataset['loan_amnt'].fillna((dataset['loan_amnt'].mean()))
dataset['funded_amnt'] = dataset['funded_amnt'].fillna((dataset['funded_amnt'].mean()))
dataset['funded_amnt_inv'] = dataset['funded_amnt_inv'].fillna((dataset['funded_amnt_inv'].mean()))
dataset['term'] = dataset['term'].fillna((dataset['term'].mean()))
dataset['int_rate'] = dataset['int_rate'].fillna((dataset['int_rate'].mean()))
dataset['emp_length'] = dataset['emp_length'].fillna((dataset['emp_length'].mean()))
dataset['annual_inc'] = dataset['annual_inc'].fillna((dataset['annual_inc'].mean()))
dataset['dti'] = dataset['dti'].fillna((dataset['dti'].mean()))
dataset['delinq_2yrs'] = dataset['delinq_2yrs'].fillna((dataset['delinq_2yrs'].mean()))
dataset['inq_last_6mths'] = dataset['inq_last_6mths'].fillna((dataset['inq_last_6mths'].mean()))
dataset['mths_since_last_delinq'] = dataset['mths_since_last_delinq'].fillna((dataset['mths_since_last_delinq'].mean()))
dataset['mths_since_last_record'] = dataset['mths_since_last_record'].fillna((dataset['mths_since_last_record'].mean()))
dataset['open_acc'] = dataset['open_acc'].fillna((dataset['open_acc'].mean()))
dataset['pub_rec'] = dataset['pub_rec'].fillna((dataset['pub_rec'].mean()))
dataset['revol_bal'] = dataset['revol_bal'].fillna((dataset['revol_bal'].mean()))
dataset['revol_util'] = dataset['revol_util'].fillna((dataset['revol_util'].mean()))
dataset['total_acc'] = dataset['total_acc'].fillna((dataset['total_acc'].mean()))
dataset['total_rec_int'] = dataset['total_rec_int'].fillna((dataset['total_rec_int'].mean()))
dataset['total_rec_late_fee'] = dataset['total_rec_late_fee'].fillna((dataset['total_rec_late_fee'].mean()))
dataset['recoveries'] = dataset['recoveries'].fillna((dataset['recoveries'].mean()))
dataset['collection_recovery_fee'] = dataset['collection_recovery_fee'].fillna((dataset['collection_recovery_fee'].mean()))
dataset['mths_since_last_major_derog'] = dataset['mths_since_last_major_derog'].fillna((dataset['mths_since_last_major_derog'].mean()))
dataset['term'] = dataset['term'].fillna((dataset['term'].mean()))

dataset['tot_cur_bal'] = dataset['tot_cur_bal'].fillna((dataset['tot_cur_bal'].mean()))
dataset['total_rev_hi_lim'] = dataset['total_rev_hi_lim'].fillna((dataset['total_rev_hi_lim'].mean()))

In [87]:
dataset

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,emp_length,annual_inc,dti,delinq_2yrs,inq_last_6mths,...,revol_util,total_acc,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,mths_since_last_major_derog,tot_cur_bal,total_rev_hi_lim,loan_status
0,14350,14350,14350.00,36,19.19,9.000000,28700.0,33.88,0.0,1.0,...,73.1,28.0,1173.84,0.00,0.00,0.00,74.000000,0.000000,30800.000000,0
1,4800,4800,4800.00,36,10.99,0.500000,65000.0,3.64,0.0,1.0,...,23.2,13.0,83.95,0.00,0.00,0.00,44.121462,0.000000,32900.000000,0
2,10000,10000,10000.00,36,7.26,2.000000,45000.0,18.42,0.0,0.0,...,31.2,19.0,56.47,0.00,0.00,0.00,44.121462,65.000000,34900.000000,0
3,15000,15000,15000.00,36,19.72,11.000000,105000.0,14.97,0.0,2.0,...,55.5,21.0,4858.62,0.00,0.00,0.00,44.121462,0.000000,24700.000000,0
4,16000,16000,16000.00,36,10.64,11.000000,52000.0,20.16,0.0,0.0,...,76.2,27.0,2296.41,0.00,0.00,0.00,44.121462,0.000000,47033.000000,0
5,15000,15000,14950.00,36,8.90,2.000000,120000.0,12.30,0.0,0.0,...,64.5,30.0,1957.24,0.00,0.00,0.00,44.121462,0.000000,29500.000000,0
6,5000,5000,4975.00,36,7.90,5.000000,75000.0,5.70,0.0,0.0,...,23.9,23.0,578.36,0.00,0.00,0.00,44.121462,1023.000000,55500.000000,1
7,6000,6000,6000.00,36,9.17,8.000000,54000.0,11.63,0.0,1.0,...,29.5,49.0,637.51,0.00,0.00,0.00,54.000000,0.000000,11800.000000,0
8,6000,6000,6000.00,36,13.99,7.000000,92000.0,30.85,0.0,0.0,...,76.6,27.0,621.72,0.00,0.00,0.00,44.121462,0.000000,62100.000000,0
9,34550,34550,34550.00,60,17.14,2.000000,72000.0,33.92,0.0,0.0,...,90.5,30.0,5535.46,0.00,0.00,0.00,44.121462,0.000000,33200.000000,0
10,25000,25000,24975.00,36,13.33,11.000000,135000.0,14.20,0.0,1.0,...,50.8,32.0,1551.58,0.00,0.00,0.00,52.000000,0.000000,47000.000000,0
11,15000,15000,15000.00,36,18.49,4.000000,76000.0,15.86,0.0,1.0,...,71.9,30.0,3726.32,0.00,0.00,0.00,82.000000,0.000000,19600.000000,1
12,18000,18000,18000.00,36,6.99,7.000000,62000.0,18.58,0.0,2.0,...,34.2,31.0,992.37,0.00,0.00,0.00,44.121462,0.000000,139900.000000,0
13,9000,9000,9000.00,36,6.03,11.000000,145000.0,15.42,0.0,0.0,...,27.2,39.0,633.42,0.00,0.00,0.00,44.121462,0.000000,43000.000000,0
14,8800,8800,8800.00,36,13.65,11.000000,80000.0,13.98,0.0,1.0,...,41.4,17.0,1521.50,0.00,0.00,0.00,44.121462,0.000000,41200.000000,1
15,8000,8000,8000.00,36,15.61,4.000000,50000.0,27.39,0.0,2.0,...,35.4,24.0,801.55,0.00,0.00,0.00,44.121462,0.000000,18500.000000,0
16,18450,18450,18450.00,60,21.70,9.000000,69000.0,24.28,0.0,0.0,...,96.2,35.0,6269.20,0.00,0.00,0.00,72.000000,0.000000,15900.000000,0
17,30750,30750,30700.00,36,16.99,6.398724,70000.0,29.13,3.0,2.0,...,99.4,35.0,7394.32,0.00,0.00,0.00,26.000000,0.000000,17400.000000,0
18,9000,9000,9000.00,36,9.99,7.000000,60000.0,19.70,0.0,0.0,...,54.7,28.0,412.36,0.00,0.00,0.00,44.121462,0.000000,17000.000000,0
19,24000,24000,24000.00,36,10.99,7.000000,130000.0,23.22,0.0,1.0,...,76.7,25.0,833.27,0.00,0.00,0.00,44.121462,0.000000,31000.000000,0
20,20000,20000,20000.00,60,17.86,9.000000,96000.0,18.31,1.0,0.0,...,68.7,28.0,843.95,0.00,0.00,0.00,18.000000,0.000000,27200.000000,0
21,12400,12400,12400.00,36,6.62,2.000000,40000.0,20.31,0.0,2.0,...,12.2,9.0,0.00,0.00,712.76,7.03,44.121462,213.562222,32080.572919,0
22,4200,4200,4200.00,36,17.57,11.000000,46000.0,31.25,1.0,0.0,...,82.4,28.0,394.08,0.00,0.00,0.00,44.121462,0.000000,25700.000000,0
23,10500,10500,10500.00,36,13.66,7.000000,60000.0,13.82,0.0,1.0,...,60.6,24.0,845.33,0.00,0.00,0.00,44.121462,0.000000,14300.000000,1
24,16000,16000,16000.00,36,7.89,0.500000,65000.0,21.54,0.0,0.0,...,54.2,30.0,398.12,0.00,0.00,0.00,44.121462,0.000000,41400.000000,0
25,23800,23800,23800.00,60,15.61,4.000000,70000.0,21.93,0.0,0.0,...,46.7,27.0,5008.50,0.00,0.00,0.00,44.121462,0.000000,43400.000000,0
26,7200,7200,7150.00,36,12.99,2.000000,37000.0,13.43,0.0,0.0,...,32.0,28.0,1047.06,0.00,0.00,0.00,47.000000,0.000000,19800.000000,1
27,19200,19200,19175.00,36,6.62,1.000000,250000.0,25.86,0.0,1.0,...,87.3,23.0,1785.13,0.00,0.00,0.00,44.121462,0.000000,33100.000000,1
28,15000,15000,15000.00,36,6.92,3.000000,90000.0,29.68,0.0,1.0,...,48.4,31.0,624.80,0.00,0.00,0.00,44.121462,0.000000,49900.000000,0
29,4000,4000,4000.00,36,17.57,2.000000,20000.0,30.79,0.0,0.0,...,58.1,9.0,52.71,0.00,0.00,0.00,44.121462,0.000000,10900.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
532398,18000,18000,18000.00,36,14.49,7.000000,75000.0,16.03,3.0,1.0,...,55.8,27.0,3119.27,0.00,0.00,0.00,52.000000,0.000000,9000.000000,0
532399,4700,4700,4700.00,36,11.99,9.000000,30000.0,17.40,0.0,0.0,...,59.5,21.0,181.26,0.00,0.00,0.00,44.121462,0.000000,7300.000000,1
532400,20000,20000,20000.00,36,9.17,4.000000,94000.0,28.25,0.0,0.0,...,46.7,31.0,0.00,0.00,0.00,0.00,44.121462,0.000000,25900.000000,0
532401,7800,7800,7800.00,36,9.99,0.500000,77500.0,23.36,0.0,1.0,...,64.5,22.0,417.12,0.00,0.00,0.00,74.000000,0.000000,21200.000000,0
532402,10400,10400,10400.00,36,7.26,0.500000,50000.0,29.40,1.0,1.0,...,55.8,25.0,402.95,0.00,0.00,0.00,44.121462,0.000000,22400.000000,0
532403,22375,22375,22375.00,60,19.19,11.000000,128000.0,5.63,0.0,1.0,...,71.0,19.0,1728.66,0.00,0.00,0.00,44.121462,0.000000,13000.000000,0
532404,8000,8000,8000.00,36,7.26,11.000000,123000.0,24.57,0.0,1.0,...,44.7,59.0,91.11,0.00,0.00,0.00,70.000000,0.000000,51100.000000,0
532405,18000,18000,18000.00,60,17.27,3.000000,62000.0,26.03,1.0,1.0,...,83.4,26.0,4778.11,0.00,0.00,0.00,44.121462,0.000000,27800.000000,1
532406,10000,10000,10000.00,36,6.24,2.000000,56000.0,11.06,0.0,1.0,...,64.0,14.0,56.62,0.00,0.00,0.00,44.121462,0.000000,17000.000000,0
532407,16000,16000,16000.00,36,7.26,11.000000,54000.0,26.31,0.0,0.0,...,81.7,11.0,446.80,0.00,0.00,0.00,44.121462,0.000000,16100.000000,0
532408,7200,7200,7200.00,36,9.17,11.000000,70000.0,14.62,0.0,0.0,...,41.0,21.0,101.37,0.00,0.00,0.00,44.121462,0.000000,26300.000000,0
532409,17625,17625,17625.00,36,16.29,11.000000,41000.0,15.83,0.0,1.0,...,93.8,16.0,4545.31,0.00,0.00,0.00,44.121462,0.000000,33000.000000,0
532410,9700,9700,8283.54,36,14.82,1.000000,37500.0,27.04,0.0,5.0,...,78.6,30.0,2367.53,0.00,0.00,0.00,44.121462,213.562222,32080.572919,1
532411,20000,20000,20000.00,36,9.67,6.000000,78000.0,29.23,0.0,1.0,...,17.6,25.0,2295.31,0.00,0.00,0.00,44.121462,0.000000,35800.000000,1
532412,7200,7200,7200.00,36,16.55,6.000000,50000.0,23.79,0.0,2.0,...,24.2,29.0,800.56,0.00,0.00,0.00,44.121462,0.000000,5400.000000,0
532413,19200,19200,19200.00,60,19.22,11.000000,153000.0,16.91,0.0,4.0,...,65.8,32.0,6206.47,25.02,0.00,0.00,44.121462,0.000000,45100.000000,0
532414,20000,20000,20000.00,36,14.49,7.000000,120000.0,9.17,0.0,0.0,...,80.8,25.0,3178.58,0.00,0.00,0.00,68.000000,0.000000,15900.000000,0
532415,10000,10000,10000.00,36,7.49,6.000000,60000.0,24.46,0.0,1.0,...,8.9,34.0,1193.39,0.00,0.00,0.00,44.121462,213.562222,32080.572919,1
532416,1800,1800,1800.00,36,16.99,11.000000,62000.0,22.45,0.0,1.0,...,78.1,30.0,382.60,0.00,0.00,0.00,44.121462,128.000000,42100.000000,0
532417,10000,10000,10000.00,36,9.99,11.000000,60000.0,19.54,0.0,0.0,...,46.0,28.0,158.82,0.00,0.00,0.00,44.121462,2070.000000,18300.000000,0
532418,10000,10000,10000.00,36,9.76,9.000000,54000.0,25.07,0.0,0.0,...,70.3,35.0,75.91,0.00,0.00,0.00,44.121462,890.000000,19700.000000,0
532419,4800,4800,4800.00,36,11.53,0.500000,45000.0,7.97,1.0,0.0,...,43.8,23.0,308.18,0.00,0.00,0.00,44.121462,0.000000,10400.000000,0
532420,5700,5700,5700.00,36,14.16,9.000000,37000.0,25.36,0.0,3.0,...,63.7,35.0,67.26,0.00,0.00,0.00,44.121462,0.000000,15600.000000,1
532421,13000,13000,13000.00,60,12.99,3.000000,55000.0,4.65,1.0,0.0,...,24.7,25.0,1916.77,0.00,0.00,0.00,7.000000,0.000000,26900.000000,0
532422,10000,10000,10000.00,36,14.33,11.000000,49900.0,20.20,0.0,1.0,...,60.0,17.0,569.12,0.00,0.00,0.00,44.121462,0.000000,24200.000000,1
532423,20000,20000,20000.00,36,12.49,11.000000,75000.0,14.53,0.0,0.0,...,63.6,34.0,2595.45,0.00,0.00,0.00,44.121462,0.000000,24800.000000,0
532424,12000,12000,12000.00,60,14.99,11.000000,59000.0,22.97,0.0,0.0,...,53.1,29.0,2182.92,0.00,0.00,0.00,44.121462,0.000000,17800.000000,0
532425,18725,18725,18725.00,60,20.80,8.000000,42504.0,27.27,0.0,1.0,...,49.9,26.0,645.32,0.00,0.00,0.00,44.121462,0.000000,24200.000000,1
532426,21000,21000,21000.00,60,16.29,1.000000,50000.0,14.91,0.0,1.0,...,89.7,14.0,4619.79,0.00,0.00,0.00,44.121462,0.000000,23300.000000,0
532427,10000,10000,10000.00,36,6.39,0.500000,53000.0,17.80,0.0,0.0,...,46.4,20.0,467.52,0.00,0.00,0.00,44.121462,0.000000,21700.000000,0

In [108]:
X=dataset.iloc[:,0:25]

In [109]:
y=dataset.iloc[:,24]

In [110]:
y

0         0
1         0
2         0
3         0
4         0
5         0
6         1
7         0
8         0
9         0
10        0
11        1
12        0
13        0
14        1
15        0
16        0
17        0
18        0
19        0
20        0
21        0
22        0
23        1
24        0
25        0
26        1
27        1
28        0
29        0
         ..
532398    0
532399    1
532400    0
532401    0
532402    0
532403    0
532404    0
532405    1
532406    0
532407    0
532408    0
532409    0
532410    1
532411    1
532412    0
532413    0
532414    0
532415    1
532416    0
532417    0
532418    0
532419    0
532420    1
532421    0
532422    1
532423    0
532424    0
532425    1
532426    0
532427    0
Name: loan_status, Length: 532428, dtype: int64

In [111]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.8, random_state=100)

In [113]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [122]:
from sklearn.decomposition import PCA
pca=PCA(n_components=14)
X_train=pca.fit_transform(X_train)
X_test=pca.transform(X_test)
variance=pca.explained_variance_ratio_

In [123]:
variance

array([0.17687325, 0.08789517, 0.07631392, 0.07123022, 0.06468422,
       0.05614965, 0.04848912, 0.04496782, 0.04010576, 0.03914046,
       0.03884958, 0.03576155, 0.03399584, 0.03191054])

In [124]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [125]:
y_pred=classifier.predict(X_train)

In [126]:
y_pred

array([0, 0, 0, ..., 1, 1, 0], dtype=int64)

In [129]:
y_test

139335    0
482223    1
297963    0
514861    0
303581    0
474723    0
330311    1
425716    0
204503    0
201728    0
203497    0
29288     1
257314    0
513291    1
129881    0
129615    0
93203     0
25770     0
505503    0
200382    0
492742    1
488035    0
293616    0
393977    0
381968    0
512853    0
112717    0
349187    0
47490     0
71608     0
         ..
81506     0
113781    0
524731    0
199196    0
222987    0
160590    0
213471    0
15767     1
161392    1
168106    0
494364    0
113932    0
399251    0
254414    1
517266    0
483437    0
109057    0
106851    0
409841    0
307077    1
146248    0
398843    0
170092    0
391908    0
140308    0
331249    0
83153     1
406328    0
311277    0
469078    0
Name: loan_status, Length: 425943, dtype: int64

In [134]:
y_pred=dataset.iloc[0:425943,24]

In [135]:
from sklearn.metrics import confusion_matrix
cf=confusion_matrix(y_test,y_pred)

In [136]:
cf

array([[248693,  76634],
       [ 76585,  24031]], dtype=int64)